./build/odysseygo \
  --public-ip-resolution-service opendns \
  --network-id=123456 \
  --http-port=9656 \
  --staking-port=9657 \
  --db-dir=./data/node4 \
  --log-dir=./data/node4/logs \
  --data-dir=./data/node4/.odysseygo \
  --genesis-file=./genesis/genesis_custom.json \
  --bootstrap-beacon-connection-timeout=5m \
  --staking-signer-key-file=data/node4/.odysseygo/staking/signer.key \
  --staking-tls-cert-file=data/node4/.odysseygo/staking/staker.crt \
  --staking-tls-key-file=data/node4/.odysseygo/staking/staker.key \
  --bootstrap-ips=127.0.0.1:9651,127.0.0.1:9653,127.0.0.1:9655,127.0.0.1:9659 \
  --bootstrap-ids=NodeID-DFRpSjRPPByYm2jtX74aCpdrcstAfpAwR,NodeID-4tGmJnmgLYDq5aL4eYTD94E3Dr637kdtD,NodeID-2u2AdhwmTZDWfD4C3ppu52uwzcqfgtz9X,NodeID-7oowrokMRzbUoDRzytLsVhSny3mPTCrJi \
  --chain-config-dir=./scripts/configs/validators/D \