name: Setup Go Compiler
description: Download go compiler and add to binaries
runs:
  using: composite
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version: "1.22.5"
    - run: go version
      shell: bash
