// Copyright (C) 2019-2023, Ava Labs, Inc. All rights reserved.
// See the file LICENSE for licensing terms.

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/DioneProtocol/odysseygo/vms/components/feecollector (interfaces: FeeCollector)

// Package feecollector is a generated GoMock package.
package feecollector

import (
	reflect "reflect"

	ids "github.com/DioneProtocol/odysseygo/ids"
	gomock "go.uber.org/mock/gomock"
)

// MockFeeCollector is a mock of FeeCollector interface.
type MockFeeCollector struct {
	ctrl     *gomock.Controller
	recorder *MockFeeCollectorMockRecorder
}

// MockFeeCollectorMockRecorder is the mock recorder for MockFeeCollector.
type MockFeeCollectorMockRecorder struct {
	mock *MockFeeCollector
}

// NewMockFeeCollector creates a new mock instance.
func NewMockFeeCollector(ctrl *gomock.Controller) *MockFeeCollector {
	mock := &MockFeeCollector{ctrl: ctrl}
	mock.recorder = &MockFeeCollectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeeCollector) EXPECT() *MockFeeCollectorMockRecorder {
	return m.recorder
}

// AddAChainValue mocks base method.
func (m *MockFeeCollector) AddAChainValue(arg0 uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAChainValue", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddAChainValue indicates an expected call of AddAChainValue.
func (mr *MockFeeCollectorMockRecorder) AddAChainValue(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAChainValue", reflect.TypeOf((*MockFeeCollector)(nil).AddAChainValue), arg0)
}

// AddDChainValue mocks base method.
func (m *MockFeeCollector) AddDChainValue(arg0 uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDChainValue", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddDChainValue indicates an expected call of AddDChainValue.
func (mr *MockFeeCollectorMockRecorder) AddDChainValue(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDChainValue", reflect.TypeOf((*MockFeeCollector)(nil).AddDChainValue), arg0)
}

// AddOrionsValue mocks base method.
func (m *MockFeeCollector) AddOrionsValue(arg0 []ids.NodeID, arg1 uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOrionsValue", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddOrionsValue indicates an expected call of AddOrionsValue.
func (mr *MockFeeCollectorMockRecorder) AddOrionsValue(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOrionsValue", reflect.TypeOf((*MockFeeCollector)(nil).AddOrionsValue), arg0, arg1)
}

// GetAChainValue mocks base method.
func (m *MockFeeCollector) GetAChainValue() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAChainValue")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// GetAChainValue indicates an expected call of GetAChainValue.
func (mr *MockFeeCollectorMockRecorder) GetAChainValue() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAChainValue", reflect.TypeOf((*MockFeeCollector)(nil).GetAChainValue))
}

// GetDChainValue mocks base method.
func (m *MockFeeCollector) GetDChainValue() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDChainValue")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// GetDChainValue indicates an expected call of GetDChainValue.
func (mr *MockFeeCollectorMockRecorder) GetDChainValue() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDChainValue", reflect.TypeOf((*MockFeeCollector)(nil).GetDChainValue))
}

// GetOrionValue mocks base method.
func (m *MockFeeCollector) GetOrionValue(arg0 ids.NodeID) uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrionValue", arg0)
	ret0, _ := ret[0].(uint64)
	return ret0
}

// GetOrionValue indicates an expected call of GetOrionValue.
func (mr *MockFeeCollectorMockRecorder) GetOrionValue(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrionValue", reflect.TypeOf((*MockFeeCollector)(nil).GetOrionValue), arg0)
}

// SubAChainValue mocks base method.
func (m *MockFeeCollector) SubAChainValue(arg0 uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubAChainValue", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubAChainValue indicates an expected call of SubAChainValue.
func (mr *MockFeeCollectorMockRecorder) SubAChainValue(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubAChainValue", reflect.TypeOf((*MockFeeCollector)(nil).SubAChainValue), arg0)
}

// SubDChainValue mocks base method.
func (m *MockFeeCollector) SubDChainValue(arg0 uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubDChainValue", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubDChainValue indicates an expected call of SubDChainValue.
func (mr *MockFeeCollectorMockRecorder) SubDChainValue(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubDChainValue", reflect.TypeOf((*MockFeeCollector)(nil).SubDChainValue), arg0)
}

// SubOrionsValue mocks base method.
func (m *MockFeeCollector) SubOrionsValue(arg0 []ids.NodeID, arg1 uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubOrionsValue", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubOrionsValue indicates an expected call of SubOrionsValue.
func (mr *MockFeeCollectorMockRecorder) SubOrionsValue(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubOrionsValue", reflect.TypeOf((*MockFeeCollector)(nil).SubOrionsValue), arg0, arg1)
}
